const productActionTypes = {
  LOAD_PRODUCTS: 'LOAD_PRODUCTS',
  ADD_PRODUCT_TO_CART: 'ADD_PRODUCT_TO_CART',
  REMOVE_PRODUCT_FROM_CART: 'REMOVE_PRODUCT_FROM_CART',
  CALCULATE_TOTAL: 'CALCULATE_TOTAL',
  REMOVE_ALL_FROM_CART: 'REMOVE_ALL_FROM_CART',
  UPDATE_DB: 'UPDATE_DB',
  ADD_ONE_UNIT: 'ADD_ONE_UNIT',
  REMOVE_ONE_UNIT: 'REMOVE_ONE_UNIT'

};

export default productActionTypes;
